Added new actions
fortinet-fortisoar/connector-recorded-future pull request #2
Opened 2024-05-31 06:29 UTC by cs-utkarsh-surana

- Added following new actions and its corresponding playbooks:
    - Get Maps List
    - Get Threat Map
    - Get Threat Map By Org ID
    - Get Malware Threat Map
    - Get Malware Threat Map By Org ID
    - Get Threat Actors List
    - Get Threat Actors Categories
    - Get Malware Categories
    - Get Third Party Risk Alert By Alert ID
    - Get Bulk Third Party Risk Alerts
    - Get Identity Novel Exposures Alert By Alert ID
    - Get Bulk Identity Novel Exposures Alerts
    - Create User List
    - Get User Lists
    - Get User List By List ID
    - Get User List Status By List ID
    - Retrieves entities on the list by list ID
    - Add Entity To User List
    - Remove Entity From User List
    - Add IOC To Recorded Future Intelligence Cloud

2024-06-03 06:05 UTC, pathansam requested changes

2024-06-03 06:05 UTC, pathansam commented on recorded-future/info.json
> +          "title": "playbook_alert_ids",
Please provide appropriate title

2024-06-03 06:05 UTC, pathansam commented on recorded-future/info.json
> +          "title": "playbook_alert_ids",
Please provide appropriate title

2024-06-03 06:05 UTC, pathansam commented on recorded-future/info.json
> +          "value": "{\n    \"additionalProp1\": {}\n  }"
Please remove default value, add in sample playbook only

2024-06-03 06:05 UTC, pathansam commented on recorded-future/info.json
> +          "title": "Timestamp",
Input type is datetime , Needs to change title,

2024-06-03 06:05 UTC, pathansam commented on recorded-future/operations.py
> +        logger.error('A connection error occurred')
Log errors to know actual issue occurred

2024-06-03 06:05 UTC, pathansam commented on recorded-future/operations.py
> +        if v:
Please modify code to handle boolean (False) and integer 0

2024-06-03 06:05 UTC, pathansam commented on recorded-future/info.json
> +          "description": "Specify the entity ID to remove.",
Please verify is this parameter optional or required

2024-06-03 06:05 UTC, pathansam commented on recorded-future/operations.py
> +        raise ConnectorError('A connection error occurred')
Log actual error , to know actual error occurred

2024-06-13 12:02 UTC, cs-prerna-joshi approved these changes

2024-06-13 12:02 UTC, merged